spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_huntly
    username: ${DB_username}
    password: ${DB_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: Duy
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 785238324222-uhveoj2d99nn8ckrh67p84cj3ic4ngug.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - email
#              - profile
  mail:
    username: ${MAIL_USERNAME}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            required: true
            enable: true
  data:
    web:
      pageable:
        one-indexed-parameters: true

outbound:
  job-huntly:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: ${REDIRECT_URI}
    grant-type: authorization_code