spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_huntly
    username: ${DB_username}
    password: ${DB_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: Duy
  mail:
    username: ${MAIL_USERNAME}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            required: true
            enable: true

